### ISSUE TITLE
problematic scores re slavery, racism, rape, etc

### ISSUE THREAD

**Issue by HP4k1h5** [conversationai/perspectiveapi#19]
![screen shot 2017-08-10 at 10 02 41 am](https://user-images.githubusercontent.com/20137484/29174038-243b6508-7db3-11e7-9709-7746d040efb5.png)
Judging from this sole example, (it's a sufficient sample size in this case, owing to the magnitude of its error), your entire project should be scrapped and started again from scratch, or not restarted at all, maybe.  
There are already countless examples of very straightforward and non-offensive opinions on a host of topics from genocide to sexual abuse that generate >.90 toxic scores. 
Your bot is no better than a word checker. 
I could have written a regex in minutes that would actually be more helpful for this. 
if it's still in a learning stage, you should not have it deliver any score at all or deliver a score that is more neutral than "toxic". just a very simple thought that should be obvious to anyone.
thanks

**Comment by iislucas** [comment]
There are indeed many false positives (and false negatives) like this. Such examples do a good job of clearly illustrating how wrong models can be, and why we advise people experimenting and using these models *not* to use them for automatic moderation, but instead use them to select what to review. It's also why we call the model 'alpha' in our documentation. 

Detection of abusive and toxic language is an active area of research (e.g. see [the ALW workshop at ACL'2017](https://sites.google.com/site/abusivelanguageworkshop2017/)), and I think you are under-estimating it's difficulty - but if you can write a regexp, I would strongly recommend doing so and sharing with the academic community along with results on the public datasets.  Our research page has more details of our work, code, the background research, and the public datasets we have contributed:  https://conversationai.github.io/

The problem with not sharing research because one is worried about bad false positives, like the one you mention above, is that it's stops research making progress at all. In particular, you cannot identify what kinds of additional data are needed, and without additional data, you can't really make the models better. I prefer instead to take a more open approach to the research, allow people to experiment with our work early, and help identify missing data and contribute more data.

**Comment by Babazon** [comment]
Sarcasm is an important part of human verbal communication. How do you plan to evaluate out of context sarcasm? Just erase it from human language?

**Comment by HP4k1h5** [comment]
I appreciate the difficulty in even attempting to do this sort of research, but that is why open source models and publicly available datasets are probably essential. Scores should be able to document more or less reasons why they are making their evaluation. and barring that, having the data and the algorithms would at least explain how and why the bot thinks the way it does. 
But even more importantly for this api, in my opinion is to de-escalate your bots rhetoric, since it is automatically associating all the negative things said in a "toxic" context with the the object of those attacks. While there may be some value in demonstrating which words are attacked the most, I don't think calling "black people" "toxic", is the right way to go about showing how much your bot learned about online harassment. 
It seems like when there is only one word, like person, or woman, or gay or indigenous, in the machine, it shouldn't pass much of judgement in most cases on those at all. Now again, if it's collecting data on attacks on any particular word, that's just data, but presenting it to the public as "likely to be considered" “toxic" = "category of person" is just so dangerous.

**Comment by iislucas** [comment]
Sarcasm is important... you don't say?
 
And indeed, there's a fair bit of work on sarcasm, e.g. see: 
 * https://arxiv.org/abs/1607.00976 
 * http://www.thesarcasmdetector.com/about/ 
 * http://www.aclweb.org/anthology/P11-2102

**Comment by iislucas** [comment]
Closing as this example has now been added as a false positive; we'll continue collecting training data and continue to try to improve the models.
