### ISSUE TITLE
Unusual traffic from your ip 

### ISSUE THREAD

**Issue by kirkshoop** [conversationai/perspectiveapi#24]
Do calls to the perspective API or 429 throttling affect the "unusual traffic" captcha prompt on google searches?

I am trying to diagnose why searches from my home network are being prompted with the captcha.

**Comment by cjadams** [comment]
The API has a 10 qps limit, so if you are staying under that rate limit, I would be very surprised if this would be the cause of any Google-wide captcha prompt. The situation that I have seen cause a captcha prompt is when a device on a users network (or a shared network like a school or workplace) has been compromised and is being used by a botnet to send DDoS attacks etc. Just to be sure though, what volume of queries are you sending?  Are you regularly hitting rate errors on our API for going above 10 qps?  A way to definitively test the issue would be to start only using the API from a cloud project instead of your home device/network and see if the problem goes away. Hope that helps!
