### ISSUE TITLE
Valid comments get high Spam values with default Spam settings

### ISSUE THREAD

**Issue by lesukk** [conversationai/perspectiveapi#34]
Example:

**Comment** `Interesting. Like to know more on the process suitable for electro plating industry`
**Score** `type:"PROBABILITY"
value:0.71243495`

**Comment** `Tempting. However, Chennai Udupi hotel dosai is the best`
**Score** `type:"PROBABILITY"
value:0.93607247`

Please let me know if you need more examples, there are many.

Maybe we need to adjust our settings?

**Comment by iislucas** [comment]
Thanks! The current SPAM classifier is still very experimental and is not as good as I'd like it; it's trained on the NYT spam dataset, but the NYT doesn't get much spam because they have human reviewers examine all comments before they are published, so people don't bother trying to spam them much. if you have a dataset of real spam, that could be used to help train it further, and we'd welcome that. We're trying to create and collect more creative commons datasets to help build better models for this and other attributes to help online conversation. You can find our form for data contribution here: https://docs.google.com/forms/d/e/1FAIpQLScAivfFHiwq08JfsHuIkTbdECLK0nSmyBi4JMvaqDrom2aVQw/viewform?c=0&w=1

**Comment by TheBlackPlague** [comment]
Isn't spam usually done on multiple messages? I believe spam is more dependant on the context of the conversation rather than just a single message. For example: `Hello` alone won't be considered as spam but `Hello` sent consequently multiple times will be considered as spam. What's your opinion on this?  @iislucas

**Comment by iislucas** [comment]
Yes, that's correct. For any serious spam filtering you'll want to know many network signals, and typically also know historical information about mail servers, is encryption used, etc etc.
