### ISSUE TITLE
Documentation is unclear on the matter of language auto-detection.

### ISSUE THREAD

**Issue by anseal** [conversationai/perspectiveapi#95]
Here https://github.com/conversationai/perspectiveapi/blob/master/2-api/methods.md#analyzecomment-request
it's said about request's languages field:
> If unspecified, the API will auto-detect the comment language.

But this
```
{"comment":{"text":"some text"},"requestedAttributes":{"TOXICITY":{}}}
```
doesn't work, as well as
```
{"comment":{"text":"some text"},"requestedAttributes":{"TOXICITY":{}}, "languages":[]}
```
and 
```
{"comment":{"text":"some text"},"requestedAttributes":{"TOXICITY":{}},"languages":["en","fr","es","de","it","pt"]}
```
But I do get a response with a single language:
```
{"comment":{"text":"some text"},"requestedAttributes":{"TOXICITY":{}}, "languages":["en"]}
```

What is the correct way to write a request with auto-detection?

**Comment by anseal** [comment]
Well, after a little bit of digging it looks like the correct way to auto-detect is
```
{"comment":{"text":"some text"},"requestedAttributes":{"TOXICITY":{}}}
```
but auto-detection sometimes fails with `LANGUAGE_NOT_SUPPORTED_BY_ATTRIBUTE`.

E.g "yo hamburger" is auto-detected as Turkish. But TOXICITY doesn't support Turkish... Wouldn't it be reasonable to limit the auto-detected languages to the supported ones?

**Comment by fynjah** [comment]
Same problem here

**Comment by oliviaredfield** [comment]
Hi there!
We tested out the example commands, one with an empty list for languages, and one with language missing, and both work. We're in the midst of updating documentation, but here are some pointers in the meantime: One language will be detected per comment. You can either use language detection or specify a single language. Alternatively, you could make separate calls with different languages in each. Language detection won't run if you specify a language. If you specify a language that doesn't match what's in the comment, the score might not make sense. If you feel confident you know the language of your text, you'll get a better outcome to identify the language rather than run autodetection.
